spring.application.name=urlshortener

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:urlshortener}
spring.datasource.username=${POSTGRES_USER:urlshortener}
spring.datasource.password=${POSTGRES_PASSWORD:urlshortener}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
