spring.application.name=urlshortener

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:urlshortener}
spring.datasource.username=${POSTGRES_USER:urlshortener}
spring.datasource.password=${POSTGRES_PASSWORD:urlshortener}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:m+9JIXpc8Yj2F7hIOoqIxMILne4JkGs7GBGtrKsP42VKsxi3nRbRHJXanTvnOKo7}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
